In [1]:
#for pandas 
import pandas as pd

#for numpy
import numpy as np

#importing keras
from keras.models import Sequential
from keras.layers import Dense

C:\Users\Ritik\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def modify(y):
    m=y.shape[0]
    ynew=np.zeros((m,10))
    for i in range(0,m):
        ynew[i,y[i]]=1
    return ynew

In [3]:
def output_submit(y,filename):
    filename=filename+".csv"
    out=[]
    ind=[]
    for i in range(0,y.shape[0]):
        hey=y[i,:].reshape(-1,1)
        out.append(np.argmax(hey))
        ind.append(i+1)
    hey=np.hstack((np.array(ind).reshape(-1,1),np.array(out).reshape(-1,1)))
    np.savetxt(filename,hey,header="ImageId,Label",delimiter=',',comments='')

In [4]:
dfl="C:/Users/Ritik/Desktop/Projects_Flash/Digit Recognizer[MNIST]/train.csv"

In [5]:
datatrain=pd.read_csv(dfl,header=0)

In [6]:
datatrain.shape

(42000, 785)

In [7]:
dfl="C:/Users/Ritik/Desktop/Projects_Flash/Digit Recognizer[MNIST]/test.csv"

In [8]:
datatest=pd.read_csv(dfl,header=0)

In [9]:
datatest.shape

(28000, 784)

In [10]:
print(datatrain.isnull().any().sum())
print(datatest.isnull().any().sum())

0
0


So there are no null or empty values in dataset(both training and testing)

In [11]:
xtrain=np.array(datatrain.iloc[:,1:])
ytrain=np.array(datatrain.iloc[:,0]).reshape(-1,1)
xtest=np.array(datatest)
print(xtrain.shape,ytrain.shape)
print(xtest.shape)

(42000, 784) (42000, 1)
(28000, 784)


In [12]:
ytrain=modify(ytrain)
print(ytrain.shape)
print(ytrain[0:5,:])

(42000, 10)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Divide xtrain and xtest by 255 so to bring all array element vlaues between 0 and 1
Then adding bias column to them

In [13]:
xtrain=xtrain/255
xtest=xtest/255
xtrain=np.hstack((np.ones(xtrain.shape[0]).reshape(-1,1),xtrain))
xtest=np.hstack((np.ones(xtest.shape[0]).reshape(-1,1),xtest))
print(xtrain.shape)
print(xtest.shape)

(42000, 785)
(28000, 785)


Now we will use Keras for building model

In [14]:
model=Sequential()
model.add(Dense(25,input_dim=785,kernel_initializer='uniform',activation='relu'))
model.add(Dense(10,kernel_initializer='uniform',activation='sigmoid'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [15]:
model.fit(xtrain,ytrain,epochs=40,batch_size=10,verbose=2)

Epoch 1/40
 - 24s - loss: 0.4205 - acc: 0.8803
Epoch 2/40
 - 20s - loss: 0.2578 - acc: 0.9255
Epoch 3/40
 - 21s - loss: 0.2165 - acc: 0.9369
Epoch 4/40
 - 22s - loss: 0.1857 - acc: 0.9446
Epoch 5/40
 - 26s - loss: 0.1640 - acc: 0.9517
Epoch 6/40
 - 37s - loss: 0.1473 - acc: 0.9565
Epoch 7/40
 - 25s - loss: 0.1344 - acc: 0.9603
Epoch 8/40
 - 27s - loss: 0.1242 - acc: 0.9627
Epoch 9/40
 - 25s - loss: 0.1140 - acc: 0.9662
Epoch 10/40
 - 25s - loss: 0.1078 - acc: 0.9678
Epoch 11/40
 - 31s - loss: 0.1003 - acc: 0.9696
Epoch 12/40
 - 31s - loss: 0.0933 - acc: 0.9718
Epoch 13/40
 - 26s - loss: 0.0882 - acc: 0.9725
Epoch 14/40
 - 25s - loss: 0.0821 - acc: 0.9745
Epoch 15/40
 - 26s - loss: 0.0786 - acc: 0.9760
Epoch 16/40
 - 24s - loss: 0.0734 - acc: 0.9774
Epoch 17/40
 - 28s - loss: 0.0703 - acc: 0.9773
Epoch 18/40
 - 30s - loss: 0.0659 - acc: 0.9785
Epoch 19/40
 - 27s - loss: 0.0622 - acc: 0.9799
Epoch 20/40
 - 29s - loss: 0.0597 - acc: 0.9816
Epoch 21/40
 - 28s - loss: 0.0575 - acc: 0.9818
E

In [16]:
prediction=model.predict(xtest)
prediction.shape

(28000, 10)

In [18]:
output_submit(prediction,"2_layer_relusigmoid_keras_submission2")