In [1]:
#for pandas 
import pandas as pd

#for numpy
import numpy as np

#for visualization
import matplotlib.pyplot as plt
import seaborn as sns

#this will help to keep track of iterations of gradient training
from IPython.display import clear_output

#importing keras
from keras.models import Sequential
from keras.layers import Dense

C:\Users\Ritik\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def modify(y):
    m=y.shape[0]
    ynew=np.zeros((m,10))
    for i in range(0,m):
        ynew[i,y[i]]=1
    return ynew

In [30]:
def output_submit(y,filename):
    filename=filename+".csv"
    out=[]
    ind=[]
    for i in range(0,y.shape[0]):
        hey=y[i,:].reshape(-1,1)
        out.append(np.argmax(hey))
        ind.append(i+1)
    hey=np.hstack((np.array(ind).reshape(-1,1),np.array(out).reshape(-1,1)))
    np.savetxt(filename,hey,header="ImageId,Label",delimiter=',',comments='')

In [3]:
dfl="C:/Users/Ritik/Desktop/Projects_Flash/Digit Recognizer[MNIST]/train.csv"

In [4]:
datatrain=pd.read_csv(dfl,header=0)

In [5]:
datatrain.shape

(42000, 785)

In [6]:
dfl="C:/Users/Ritik/Desktop/Projects_Flash/Digit Recognizer[MNIST]/test.csv"

In [7]:
datatest=pd.read_csv(dfl,header=0)

In [8]:
datatest.shape

(28000, 784)

In [9]:
print(datatrain.isnull().any().sum())
print(datatest.isnull().any().sum())

0
0


So there are no null or empty values in dataset(both training and testing)

In [10]:
xtrain=np.array(datatrain.iloc[:,1:])
ytrain=np.array(datatrain.iloc[:,0]).reshape(-1,1)
xtest=np.array(datatest)
print(xtrain.shape,ytrain.shape)
print(xtest.shape)

(42000, 784) (42000, 1)
(28000, 784)


In [11]:
ytrain=modify(ytrain)
print(ytrain.shape)
print(ytrain[0:5,:])

(42000, 10)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Divide xtrain and xtest by 255 so to bring all array element vlaues between 0 and 1
Then adding bias column to them

In [12]:
xtrain=xtrain/255
xtest=xtest/255
xtrain=np.hstack((np.ones(xtrain.shape[0]).reshape(-1,1),xtrain))
xtest=np.hstack((np.ones(xtest.shape[0]).reshape(-1,1),xtest))
print(xtrain.shape)
print(xtest.shape)

(42000, 785)
(28000, 785)


Now we will use Keras for building model

In [17]:
model=Sequential()
model.add(Dense(25,input_dim=785,kernel_initializer='uniform',activation='sigmoid'))
model.add(Dense(10,kernel_initializer='uniform',activation='sigmoid'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
model.fit(xtrain,ytrain,epochs=40,batch_size=10,verbose=2)

Epoch 1/40
 - 28s - loss: 0.6658 - acc: 0.8545
Epoch 2/40
 - 27s - loss: 0.2552 - acc: 0.9285
Epoch 3/40
 - 26s - loss: 0.2064 - acc: 0.9414
Epoch 4/40
 - 26s - loss: 0.1790 - acc: 0.9491
Epoch 5/40
 - 26s - loss: 0.1609 - acc: 0.9541
Epoch 6/40
 - 27s - loss: 0.1474 - acc: 0.9570
Epoch 7/40
 - 26s - loss: 0.1359 - acc: 0.9612
Epoch 8/40
 - 27s - loss: 0.1267 - acc: 0.9629
Epoch 9/40
 - 23s - loss: 0.1184 - acc: 0.9660
Epoch 10/40
 - 24s - loss: 0.1122 - acc: 0.9680
Epoch 11/40
 - 25s - loss: 0.1059 - acc: 0.9700
Epoch 12/40
 - 24s - loss: 0.1009 - acc: 0.9717
Epoch 13/40
 - 26s - loss: 0.0966 - acc: 0.9725
Epoch 14/40
 - 26s - loss: 0.0916 - acc: 0.9739
Epoch 15/40
 - 26s - loss: 0.0881 - acc: 0.9748
Epoch 16/40
 - 27s - loss: 0.0839 - acc: 0.9766
Epoch 17/40
 - 26s - loss: 0.0811 - acc: 0.9769
Epoch 18/40
 - 26s - loss: 0.0778 - acc: 0.9782
Epoch 19/40
 - 26s - loss: 0.0754 - acc: 0.9788
Epoch 20/40
 - 27s - loss: 0.0723 - acc: 0.9796
Epoch 21/40
 - 27s - loss: 0.0695 - acc: 0.9808
E

In [24]:
prediction=model.predict(xtest)
prediction.shape

(28000, 10)

In [31]:
output_submit(prediction,"2_layer_sigmoid_keras_submission_1")