In [2]:
#for pandas 
import pandas as pd

#for numpy
import numpy as np

#importing keras

from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Dropout,Flatten

In [3]:
def modify(y):
    m=y.shape[0]
    ynew=np.zeros((m,10))
    for i in range(0,m):
        ynew[i,y[i]]=1
    return ynew

In [4]:
def output_submit(y,filename):
    filename=filename+".csv"
    out=[]
    ind=[]
    for i in range(0,y.shape[0]):
        hey=y[i,:].reshape(-1,1)
        out.append(np.argmax(hey))
        ind.append(i+1)
    hey=np.hstack((np.array(ind).reshape(-1,1),np.array(out).reshape(-1,1)))
    np.savetxt(filename,hey,header="ImageId,Label",delimiter=',',comments='')

In [5]:
dfl="C:/Users/Ritik/Desktop/Projects_Flash/Digit Recognizer[MNIST]/train.csv"

In [6]:
datatrain=pd.read_csv(dfl,header=0)

In [7]:
datatrain.shape

(42000, 785)

In [8]:
dfl="C:/Users/Ritik/Desktop/Projects_Flash/Digit Recognizer[MNIST]/test.csv"

In [9]:
datatest=pd.read_csv(dfl,header=0)

In [10]:
datatest.shape

(28000, 784)

In [11]:
print(datatrain.isnull().any().sum())
print(datatest.isnull().any().sum())

0
0


So there are no null or empty values in dataset(both training and testing)

In [12]:
xtrain=np.array(datatrain.iloc[:,1:])
ytrain=np.array(datatrain.iloc[:,0]).reshape(-1,1)
xtest=np.array(datatest)
print(xtrain.shape,ytrain.shape)
print(xtest.shape)

(42000, 784) (42000, 1)
(28000, 784)


In [13]:
ytrain=modify(ytrain)
print(ytrain.shape)
print(ytrain[0:5,:])

(42000, 10)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Divide xtrain and xtest by 255 so to bring all array element vlaues between 0 and 1

In [14]:
xtrain=xtrain/255
xtest=xtest/255

In [15]:
xtrain=xtrain.reshape(xtrain.shape[0],28,28,1)
xtest=xtest.reshape(xtest.shape[0],28,28,1)
print(xtrain.shape)
print(xtest.shape)

(42000, 28, 28, 1)
(28000, 28, 28, 1)


Now we will use Keras for building model

In [ ]:
model = Sequential()
 
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.6))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.fit(xtrain,ytrain,epochs=20,batch_size=200,verbose=2)

Epoch 1/20
 - 134s - loss: 0.0558 - acc: 0.9806
Epoch 2/20
 - 322s - loss: 0.0199 - acc: 0.9932
Epoch 3/20
 - 328s - loss: 0.0138 - acc: 0.9953
Epoch 4/20
 - 287s - loss: 0.0112 - acc: 0.9961
Epoch 5/20
 - 302s - loss: 0.0093 - acc: 0.9968
Epoch 6/20
 - 256s - loss: 0.0083 - acc: 0.9971
Epoch 7/20
 - 296s - loss: 0.0071 - acc: 0.9976
Epoch 8/20
 - 307s - loss: 0.0063 - acc: 0.9978
Epoch 9/20
 - 248s - loss: 0.0060 - acc: 0.9979
Epoch 10/20
 - 255s - loss: 0.0051 - acc: 0.9982
Epoch 11/20
 - 307s - loss: 0.0046 - acc: 0.9984
Epoch 12/20
 - 364s - loss: 0.0046 - acc: 0.9984
Epoch 13/20
 - 454s - loss: 0.0041 - acc: 0.9986
Epoch 14/20
 - 277s - loss: 0.0040 - acc: 0.9986
Epoch 15/20
 - 303s - loss: 0.0036 - acc: 0.9988
Epoch 16/20
 - 312s - loss: 0.0030 - acc: 0.9989
Epoch 17/20
 - 287s - loss: 0.0033 - acc: 0.9988
Epoch 18/20
 - 313s - loss: 0.0034 - acc: 0.9989
Epoch 19/20
 - 291s - loss: 0.0030 - acc: 0.9989
Epoch 20/20


In [ ]:
prediction=model.predict(xtest)
prediction.shape

In [ ]:
output_submit(prediction,"relusigmoid_keras_submission5")